export const WILAYA_DATA = {
  "Adrar": { name_ar: "أدرار",  capital: "Adrar", region: "South", fact_ar: "ثاني أكبر ولاية في الجزائر وتشتهر بالقصور والفوقارات.", fact: "The second largest province in Algeria." },
  "Timimoune": { name_ar: "تيميمون",  capital: "Timimoun", region: "South", fact_ar: "الواحة الحمراء وقبلة سياحية عالمية.", fact: "Famous for its red ochre architecture and oases." },
  "Bordj Badji Mokhtar": { name_ar: "برج باجي مختار",  capital: "Bordj Badji Mokhtar", region: "South", fact_ar: "منطقة حدودية هامة في أقصى الجنوب.", fact: "Located deep in the Sahara Desert near the Malian border." },
  "In Guezzam": { name_ar: "عين قزام",  capital: "In Guezzam", region: "South", fact_ar: "ولاية حدودية أقصى جنوب البلاد مع النيجر.", fact: "The southernmost province of Algeria, bordering Niger." },
  "Tamanrasset": { name_ar: "تمنراست",  capital: "Tamanrasset", region: "South", fact_ar: "أكبر ولاية في الجزائر مساحة، موطن جبال الهقار.", fact: "Located in the Ahaggar Mountains in the deep south." },
  "Djanet": { name_ar: "جانت",  capital: "Djanet", region: "South", fact_ar: "واحة خلابة وبوابة جبال الطاسيلي.", fact: "An oasis city famous for the Tassili n'Ajjer National Park." },
  "Illizi": { name_ar: "إليزي",  capital: "Illizi", region: "South", fact_ar: "تضم حظيرة الطاسيلي ناجر الأثرية.", fact: "Home to the Tassili n'Ajjer national park with prehistoric rock art." },
  "Ouargla": { name_ar: "ورقلة",  capital: "Ouargla", region: "South", fact_ar: "من أهم المدن المنتجة للنفط (حاسي مسعود).", fact: "A major oil and gas producing region." },
  "In Salah": { name_ar: "عين صالح",  capital: "In Salah", region: "South", fact_ar: "من أكثر المدن حرارة وتشتهر بالغاز.", fact: "One of the hottest inhabited places on Earth." },
  "Béni Abbès": { name_ar: "بني عباس",  capital: "Béni Abbès", region: "South", fact_ar: "تسمى جوهرة الساورة.", fact: "Known as the White Oasis or Pearl of the Saoura." },
  "Tindouf": { name_ar: "تندوف",  capital: "Tindouf", region: "South", fact_ar: "تقع في أقصى الجنوب الغربي وتتميز بالصناعة المنجمية.", fact: "Located in the far west, bordering Morocco, Mauritania, and Western Sahara." },
  "Béchar": { name_ar: "بشار",  capital: "Béchar", region: "South", fact_ar: "مدينة صحراوية هامة ومركز منجمي (الفحم).", fact: "A prominent oasis town in the Sahara." },
  "Naâma": { name_ar: "النعامة",  capital: "Naâma", region: "West", fact_ar: "موطن واحة تيوث السياحية والسهوب.", fact: "A steppe region known for its pastoralism." },
  "Sidi Bel Abbès": { name_ar: "سيدي بلعباس",  capital: "Sidi Bel Abbès", region: "West", fact_ar: "كانت قديماً مقراً للفيلق الأجنبي الفرنسي.", fact: "Historically connected to the French Foreign Legion." },
  "Tlemcen": { name_ar: "تلمسان",  capital: "Tlemcen", region: "West", fact_ar: "عاصمة الزيانيين وتشتهر بالآثار الأندلسية.", fact: "Renowned for its Moorish architecture." },
  "Aïn Témouchent": { name_ar: "عين تموشنت",  capital: "Aïn Témouchent", region: "West", fact_ar: "مدينة ساحلية وقطب سياحي واعد في الغرب.", fact: "A beautiful coastal region in the northwest." },
  "Oran": { name_ar: "وهران",  capital: "Oran", region: "West", fact_ar: "الباهية، ثاني أكبر مدينة في الجزائر وعاصمة الغرب.", fact: "The second largest city, famous for Rai music." },
  "Saïda": { name_ar: "سعيدة",  capital: "Saïda", region: "West", fact_ar: "معروفة بينابيع المياه المعدنية.", fact: "Known for its mineral water springs." },
  "Mascara": { name_ar: "معسکر",  capital: "Mascara", region: "West", fact_ar: "عاصمة الأمير عبد القادر.", fact: "The capital of Emir Abdelkader's resistance state." },
  "El Bayadh": { name_ar: "البيض",  capital: "El Bayadh", region: "West", fact_ar: "تشتهر بإنتاج اللحوم الحمراء والنقوش الصخرية.", fact: "A high-altitude steppe region." },
  "Tiaret": { name_ar: "تيارت",  capital: "Tiaret", region: "West", fact_ar: "معروفة بتربية الخيول الأصيلة.", fact: "Famous for its Arabian horses." },
  "Relizane": { name_ar: "غلیزان",  capital: "Relizane", region: "West", fact_ar: "ولاية فلاحية هامة في حوض الشلف.", fact: "Located on the Mina river, an important agricultural hub." },
  "Mostaganem": { name_ar: "مستغانم",  capital: "Mostaganem", region: "West", fact_ar: "مدينة ساحلية وتاريخية وحاضرة صوفية.", fact: "A beautiful coastal city known for agriculture and port." },
  "Laghouat": { name_ar: "الأغواط",  capital: "Laghouat", region: "Central", fact_ar: "تعرف بعاصمة السهوب وتعتبر بوابة الصحراء.", fact: "Known for its dates and traditional carpets." },
  "El Menia": { name_ar: "المنيعة",  capital: "El Menia", region: "South", fact_ar: "تتميز ببساتينها وقلعتها التاريخية.", fact: "Historically known as El Goléa, a charming oasis." },
  "Tissemsilt": { name_ar: "تسمسيلت",  capital: "Tissemsilt", region: "West", fact_ar: "تضم الحظيرة الوطنية لثنية الحد.", fact: "Known for the cedar forests of Théniet El Had National Park." },
  "Ghardaia": { name_ar: "غرداية",  capital: "Ghardaïa", region: "South", fact_ar: "تتميز بوادي ميزاب وهندستها المعمارية الفريدة.", fact: "Located in the M'zab valley, known for its unique architecture." },
  "Chlef": { name_ar: "الشلف",  capital: "Chlef", region: "North", fact_ar: "كانت تسمى الأصنام، دمرها زلزال عام 1980.", fact: "Formerly known as El Asnam." },
  "Aïn Defla": { name_ar: "عين الدفلى",  capital: "Aïn Defla", region: "North", fact_ar: "عاصمة الفلاحة وتشتهر بإنتاج البطاطا.", fact: "A major agricultural region, especially for potatoes." },
  "Ouled Djellal": { name_ar: "اولاد جلال",  capital: "Ouled Djellal", region: "East", fact_ar: "معروفة بتربية الأغنام وبسلالتها الخاصة.", fact: "Known for the quality of its sheep." },
  "Tipaza": { name_ar: "تيبازة",  capital: "Tipaza", region: "North", fact_ar: "مدينة ساحلية شهيرة بآثارها الرومانية المحاذية للبحر.", fact: "Famous for its spectacular Roman ruins on the Mediterranean coast." },
  "Médéa": { name_ar: "المدية",  capital: "Médéa", region: "North", fact_ar: "عاصمة بايلك التيطري قديماً وتشتهر بالكروم.", fact: "A city in the Tell Atlas, known for its agriculture." },
  "Algiers": { name_ar: "الجزائر",  capital: "Algiers", region: "North", fact_ar: "العاصمة وتسمى الجزائر البيضاء.", fact: "The capital and largest city of Algeria." },
  "Blida": { name_ar: "البليدة",  capital: "Blida", region: "North", fact_ar: "مدينة الورود وتقع عند سفح جبال الشريعة.", fact: "Known as the City of Roses." },
  "Tizi Ouzou": { name_ar: "تيزي وزو",  capital: "Tizi Ouzou", region: "North", fact_ar: "عاصمة منطقة القبائل الكبرى.", fact: "The cultural capital of the Kabylia region." },
  "Bouira": { name_ar: "البويرة",  capital: "Bouira", region: "North", fact_ar: "تضم جبال تيكجدة السياحية الشهيرة.", fact: "Home to the Tikjda ski resort in the Djurdjura mountains." },
  "M'Sila": { name_ar: "المسيلة",  capital: "M'Sila", region: "Central", fact_ar: "تحتضن قلعة بني حماد التاريخية.", fact: "Home to the historic site of Al Qal'a of Beni Hammad." },
  "Djelfa": { name_ar: "الجلفة",  capital: "Djelfa", region: "Central", fact_ar: "تشتهر بتربية المواشي (أولاد نايل).", fact: "Famous for its livestock and sheep." },
  "Béjaïa": { name_ar: "بجاية",  capital: "Béjaïa", region: "North", fact_ar: "مدينة ساحلية وتاريخية هامة في منطقة القبائل.", fact: "A major Mediterranean port city." },
  "Sétif": { name_ar: "سطيف",  capital: "Sétif", region: "East", fact_ar: "مدينة عين الفوارة وثاني أهم مدينة اقتصادية.", fact: "One of the most important commercial centers in eastern Algeria." },
  "Bordj Bou Arreridj": { name_ar: "برج بوعريريج",  capital: "Bordj Bou Arréridj", region: "East", fact_ar: "تعتبر عاصمة الإلكترونيات في الجزائر.", fact: "Often called the electronics capital of Algeria." },
  "Jijel": { name_ar: "جيجل",  capital: "Jijel", region: "North", fact_ar: "تشتهر بالكورنيش الساحلي وغابات الكورنيش.", fact: "Known for its beautiful coastal corniche and beaches." },
  "Batna": { name_ar: "باتنة",  capital: "Batna", region: "East", fact_ar: "عاصمة الأوراس، قريبة من آثار تيمقاد الرومانية.", fact: "Home to the ancient Roman ruins of Timgad." },
  "Biskra": { name_ar: "بسكرة",  capital: "Biskra", region: "East", fact_ar: "تشتهر بإنتاج أجود أنواع التمور (دقلة نور).", fact: "Known as the capital of dates in Algeria." },
  "El M'Ghair": { name_ar: "المغير",  capital: "El M'Ghair", region: "South", fact_ar: "تقع في شمال شرق الصحراء وتمتد عبر وادي ريغ.", fact: "Located in the northeast of the Sahara." },
  "Touggourt": { name_ar: "تقرت",  capital: "Touggourt", region: "South", fact_ar: "منطقة واحات تاريخية في الجنوب الشرقي.", fact: "A historic city known for its vast date palm groves." },
  "El Oued": { name_ar: "الوادي",  capital: "El Oued", region: "South", fact_ar: "مدينة الألف قبة وقبة.", fact: "Known as the City of a Thousand Domes." },
  "Khenchela": { name_ar: "خنشلة",  capital: "Khenchela", region: "East", fact_ar: "تشتهر بصناعة الزرابي وحمامات الصالحين.", fact: "Located in the Aurès mountains, known for its apples." },
  "Tébessa": { name_ar: "تبسة",  capital: "Tébessa", region: "East", fact_ar: "غنية بالآثار الرومانية والمناجم.", fact: "Contains many Roman monuments and ruins." },
  "Oum El Bouaghi": { name_ar: "أم الـبـواقي",  capital: "Oum el Bouaghi", region: "East", fact_ar: "تشتهر بالزراعة وسهولها الواسعة.", fact: "Located in the Aurès region." },
  "Souk Ahras": { name_ar: "سوق أهراس",  capital: "Souk Ahras", region: "East", fact_ar: "مسقط رأس القديس أوغسطين وتاريخ روماني قديم.", fact: "Birthplace of St. Augustine (Tagaste)." },
  "Guelma": { name_ar: "قالمة",  capital: "Guelma", region: "East", fact_ar: "معروفة بحماماتها المعدنية الحارة (حمام المسخوطين).", fact: "Known for its thermal springs like Hammam Meskhoutine." },
  "El Tarf": { name_ar: "الطارف",  capital: "El Tarf", region: "East", fact_ar: "تشتهر بالمرجان وحظيرة القالة الوطنية.", fact: "Bordering Tunisia, home to the El Kala National Park." },
  "Annaba": { name_ar: "عنابة",  capital: "Annaba", region: "North", fact_ar: "تسمى بونة وتضم كنيسة القديس أوغسطين.", fact: "The ancient city of Hippo Regius, home of St. Augustine." },
  "Skikda": { name_ar: "سكيكدة",  capital: "Skikda", region: "North", fact_ar: "تضم أحد أهم الموانئ النفطية ومصانع البتروكيماويات.", fact: "A major port and petrochemical hub." },
  "Mila": { name_ar: "ميلة",  capital: "Mila", region: "East", fact_ar: "تضم سد بني هارون، الأكبر في الجزائر.", fact: "Home to the massive Beni Haroun dam." },
  "Constantine": { name_ar: "قسنطينة",  capital: "Constantine", region: "East", fact_ar: "مدينة الجسور المعلقة وعاصمة الشرق.", fact: "The City of Bridges, built on a spectacular ravine." },
  "Boumerdès": { name_ar: "بومرداس",  capital: "Boumerdès", region: "North", fact_ar: "ولاية ساحلية قريبة من العاصمة وذات طابع فلاحي.", fact: "A coastal province known for its universities and research institutes." }
};
